auth/urls.py
from django.urls import path

from auth import views


app_name = "auth"

urlpatterns = [
    path("register/", views.register_choose, name="register"),
    path("register/visitor", views.register_visitor, name="register_visitor"),
    path("register/organizer", views.register_organizer, name="register_organizer"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

e_wallet/urls.py
from django.urls import path

from e_wallet import views


app_name = "e_wallet"

urlpatterns = [
    path("", views.wallet_list, name="list"),
    path("top-up/<str:account_number>", views.top_up, name="top_up"),
]

event/urls.py
from django.urls import path

from event import views


app_name = "event"

urlpatterns = [
    path("", views.event_list, name="list"),
    path("create", views.create, name="create"),
    path("<str:id_event>/edit", views.edit, name="edit")
]

event_plus/urls.py
from django.urls import path, include

import event.views


urlpatterns = [
    path("", event.views.event_list),
    path("auth/", include("auth.urls")),
    path("profile/", include("user.urls")),
    path("e-wallet/", include("e_wallet.urls")),
    path("event/", include("event.urls")),
    path("event/<str:id>/tiket/", include("tiket.urls")),
]

tiket/urls.py
from django.urls import path

from tiket import views


app_name = "tiket"

urlpatterns = [
    path("buy", views.tiket_list, name="buy"),
    path("transaksi/", views.transactions, name="transaksi"),
    path("transaksi/update", views.update, name="update"),
]

user/urls.py
from django.urls import path

from user import views


app_name = "user"

urlpatterns = [
    path("", views.profile, name="profile"),
    path("edit", views.edit_profile, name="edit_profile"),
]

e_wallet/forms.py
from django import forms
from django.db import connection


class EWalletUpdateForm(forms.Form):
    email_pengunjung = forms.EmailField(disabled=True)
    nama = forms.CharField(disabled=True, label="Nama Dompet")
    no_akun = forms.CharField(disabled=True, label="No. Akun")
    saldo = forms.FloatField(disabled=True, label="Saldo")
    top_up_value = forms.IntegerField(min_value=0, max_value=int(1e9), initial=0)
    total_balance = forms.FloatField(min_value=0, initial=0)

    def save(self):
        where_data = ["email_pengunjung", "no_akun"]
        where_args = " AND ".join([d + "=%s" for d in where_data])

        with connection.cursor() as cursor:
            cursor.execute(
                f"UPDATE dompet_digital SET saldo=%s WHERE {where_args}",
                [self.cleaned_data["total_balance"]]
                + [self.initial[d] for d in where_data],
            )

event/forms.py
from django import forms

class EventForm(EventForm):
    nama_event = forms.CharField(max_length=20, label="Nama Event")
    deskripsi_event = forms.CharField(max_length=20, label="Deskripsi Event")
    tema_event = forms.CharField(max_length=20, label="Tema Event")

    def save(self):
        super().save()

        if self.for_update:
            # TODO: Update data in Event table
            pass

        else:
            # TODO: Save data to Event table
            pass

tiket/forms.py
from django import forms


class PesanTicket(forms.Form):
    nama_pemesan = forms.CharField(disabled=True)
    email_pemesan = forms.EmailField(disabled=True)

e_wallet/views.py
from django.shortcuts import render, redirect

from auth.decorators import login_required, role_required
from e_wallet.forms import EWalletUpdateForm
from e_wallet.utils import get_wallet_list, get_wallet
from user.utils import get_user_data


@login_required()
@role_required("visitor")
def wallet_list(request):
    email = request.session["email"]
    role = request.session["role"]

    context = {
        "user": get_user_data(email, role),
        "wallets": get_wallet_list(email),
    }
    return render(request, "wallet_list.html", context)


@login_required()
@role_required("visitor")
def top_up(request, account_number):
    email = request.session["email"]
    role = request.session["role"]
    user_data = get_user_data(email, role)
    wallet_data = get_wallet(email, account_number)
    wallet = EWalletUpdateForm(initial=wallet_data)

    if request.method == "POST":
        wallet = EWalletUpdateForm(request.POST, initial=wallet_data)

        if wallet.is_valid():
            wallet.save()

            return redirect("e_wallet:list")

    context = {
        "user": user_data,
        "wallet": wallet,
    }
    return render(request, "top_up.html", context)

event/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from auth.decorators import login_required, role_required
from event.utils import get_event_list


def event_list(request):
    list_events = get_event_list()
    paginator = Paginator(list_events, 10)

    page_number = request.GET.get("page", 1)
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
    }
    return render(request, "event_list.html", context)


@login_required()
@role_required("organizer")
def edit(request, id_event):
    email = request.session["email"]
    role = request.session["role"]
    return render(request, "edit_event.html")


@login_required()
@role_required("organizer")
def create(request):
    email = request.session["email"]
    role = request.session["role"]
    return render(request, "create_event.html")

tiket/views.py
from django.shortcuts import render, redirect

from auth.decorators import login_required, role_required
from tiket.utils import get_ticket_list, get_event_desc, get_transaksi_list


@login_required()
@role_required("visitor")
def tiket_list(request, id_event):
    email = request.session["email"]
    role = request.session["role"]

    context = {
        "desc": get_event_desc(),
        "tickets": get_ticket_list(),
    }

    return render(request, "pesan_tiket.html", context)


@login_required()
@role_required("visitor")
def transactions(request):
    email = request.session["email"]
    role = request.session["role"]

    context = {
        "transactions": get_transaksi_list(),
    }

    return render(request, "transaksi_tiket.html", context)


@login_required()
@role_required("visitor")
def update(request):
    email = request.session["email"]
    role = request.session["role"]

    context = {
        "desc": get_event_desc(),
        "tickets": get_ticket_list(),
    }

    return render(request, "update_transaksi.html", context)

user/views.py
from django.shortcuts import render, redirect

from auth.decorators import login_required
from user.utils import get_user_data, get_update_form


@login_required()
def profile(request):
    email = request.session["email"]
    role = request.session["role"]

    user_data = get_user_data(email, role)
    form = get_update_form(role, user_data)

    context = {"form": form}
    return render(request, "profile.html", context)


@login_required()
def edit_profile(request):
    email = request.session["email"]
    role = request.session["role"]

    user_data = get_user_data(email, role)
    form = get_update_form(role, user_data)

    if request.method == "POST":
        form = get_update_form(role, request.POST, user_data)

        if form.is_valid():
            form.save()

            request.session["email"] = form.cleaned_data["email"]
            return redirect("user:profile")

    context = {"form": form}
    return render(request, "edit_profile.html", context)

e_wallet/templates/top_up.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'top_up.css' %}">
{% endblock %}

{% block title %} Dompet {% endblock %}

{% block body %}
<div class="card">
  <h2 class="card-title">Tambah Saldo</h2>

  <div class="card-content">
    <form action="" method="post">
      {% csrf_token %}
      <table class="visitor-info">
        <tr>
          <td>Nama</td>
          <td class="value">: {{ user.nama_depan }} {{ user.nama_belakang }}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td class="value">: {{ user.email }}</td>
          <input type="hidden" name="email_pengunjung" value="{{ user.email }}">
        </tr>
        <tr>
          <td>Nama Dompet</td>
          <td class="value">: {{ wallet.nama.value }}</td>
          <input type="hidden" name="nama" value="{{ wallet.nama.value }}">
        </tr>
        <tr>
          <td>No. Akun</td>
          <td class="value">: {{ wallet.no_akun.value }}</td>
          <input type="hidden" name="no_akun" value="{{ wallet.no_akun.value }}">
        </tr>
        <tr>
          <td>Saldo saat ini</td>
          <td class="value">: Rp{{ wallet.saldo.value|money }}</td>
        </tr>
        <tr>
          <td>Nominal Top Up</td>
          <td class="value">: Rp{{ wallet.top_up_value }}</td>
        </tr>
        <tr>
          <td></td>
          <td class="value">{{ wallet.top_up_value.errors }}</td>
        </tr>
        <tr>
          <td>Saldo setelah Top Up</td>
          <td class="value" id="total-balance-display">: Rp{{ wallet.saldo.value|money }}</td>
          <input type="hidden" name="total_balance" id="total-balance-value" value="{{ wallet.saldo.value }}">
        </tr>
      </table>
      <div class="btn-wrapper">
        <input type="submit" value="Top Up" class="btn btn-warning"
          onclick="return confirm(`Anda akan melakukan topup sebesar Rp${moneyFormat(topUpValue.value)}\nSaldo anda akan menjadi Rp${moneyFormat(totalBalanceValue.value)}`);"
        >
        <a href="{% url 'e_wallet:list' %}">
          <button class="btn btn-danger" type="button">Cancel</button>
        </a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
  const topUpValue = document.querySelector("#id_top_up_value");
  const totalBalanceDisplay = document.querySelector("#total-balance-display");
  const totalBalanceValue = document.querySelector("#total-balance-value");
  const currentBalance = parseFloat({{ wallet.saldo.value }});

  function submit() {
    return confirm(`Anda akan melakukan topup sebesar ${moneyFormat(topUpValue.value)}\nSaldo anda akan menjadi ${totalBalanceValue.value}`);
  }
  
  function moneyFormat(x) {
    x = x.toString().split(".");
    return parseInt(x[0], 10)
      .toString()
      .replace(/\B(?=(\d{3})+(?!\d))/g, ".")
      + (x[1] ? "," + x[1] : "");
  }

  topUpValue.addEventListener("keyup", () => {
    topUpValue.value = topUpValue.value ? parseInt(topUpValue.value) : 0;
    val = parseInt(topUpValue.value);
    totalBalanceDisplay.innerHTML = ": Rp" + moneyFormat(currentBalance + val);
    totalBalanceValue.value = currentBalance + val;
  });
</script>
{% endblock %}

e_wallet/templates/wallet_list.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'wallet_list.css' %}">
{% endblock %}

{% block title %} Dompet {% endblock %}

{% block body %}
<div class="card">
  <h2 class="card-title">Dompet Saya</h2>

  <div class="card-content">
    <table class="visitor-info">
      <tr>
        <td>Nama</td>
        <td class="value">: {{ user.nama_depan }} {{ user.nama_belakang }}</td>
      </tr>
      <tr>
        <td>Email</td>
        <td class="value">: {{ user.email }}</td>
      </tr>
    </table>
    <table class="wallet-list">
      <tr>
        <th>No.</th>
        <th>Nama Dompet</th>
        <th>No. Akun</th>
        <th>Saldo (Rp)</th>
        <th>Top Up Saldo</th>
      </tr>
      {% for wallet in wallets %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ wallet.nama }}</td>
          <td>{{ wallet.no_akun }}</td>
          <td>{{ wallet.saldo|money }}</td>
          <td>
            <a class="btn btn-warning" href="{% url 'e_wallet:top_up' wallet.no_akun %}">
              Top Up
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

event/templates/create_event.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'pesan_tiket.css' %}">
{% endblock %}

{% block title %} Pesan Tiket {% endblock %}

{% block body %}
<div class="card">
    <h2 class="card-title">Buat event baru</h2>

    <div class="card-content">
        <div class="desc" id="ticket-list">
            <form>
                <p>Nama Event: <input type="text" name="nama_event"></p>
                <p>Deskripsi Event: <input type="text" name="deskripsi"></p>
                <p>Tema: <input type="text" name="tema"></p>
                <p>Tanggal Mulai: <input type="text" name="tanggal_mulai"></p>
                <p>Tanggal Selesai: <input type="text" name="tanggal_selesai"></p>
                <p>Jam Mulai: <input type="text" name="jam_mulai"></p>
                <p>Jam Selesai: <input type="text" name="jam_selesai"></p>
                <p>Tipe Event: <input type="text" name="tipe"></p>
            </form>
        </div>
        <ul class="list">
            <p>Lokasi Event</p>
            <li id="ticket-list" style="margin-bottom: 8px;">
                <form>
                    <input type="text" name="nama_gedung">
                    <input type="text" name="kota">
                    <input type="text" name="alamat">
                    <button type="button">Hapus row</button>
                </form>
                <form>
                    <input type="text" name="nama_gedung">
                    <input type="text" name="kota">
                    <input type="text" name="alamat">
                    <button type="button">Hapus row</button>
                </form>
            </li>
            <button type="button">Tambah row</button>
            <p>Daftar Kelas Tiket</p>
            <li id="ticket-list" style="margin-bottom: 8px;">
                <form>
                    <input type="text" name="nama_kelas">
                    <input type="text" name="tarif">
                    <input type="text" name="kapasitas">
                    <button type="button">Hapus row</button>
                </form>
                <form>
                    <input type="text" name="nama_kelas">
                    <input type="text" name="tarif">
                    <input type="text" name="kapasitas">
                    <button type="button">Hapus row</button>
                </form>
            </li>
            <button type="button">Tambah row</button>
        </ul>

        <div class="transaction">
            <button type="button">Create Event</button>
            <button type="button">Cancel</button>
        </div>
    </div>

</div>

{% endblock %}

event/templates/edit_event.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'pesan_tiket.css' %}">
{% endblock %}

{% block title %} Pesan Tiket {% endblock %}

{% block body %}
<div class="card">
    <h2 class="card-title">Update Event</h2>

    <div class="card-content">
        <div class="desc" id="ticket-list">
            <form>
                <p>Nama Event: <input type="text" name="nama_event"></p>
                <p>Deskripsi Event: <input type="text" name="deskripsi"></p>
                <p>Tema: <input type="text" name="tema"></p>
                <p>Tanggal Mulai: <input type="text" name="tanggal_mulai"></p>
                <p>Tanggal Selesai: <input type="text" name="tanggal_selesai"></p>
                <p>Jam Mulai: <input type="text" name="jam_mulai"></p>
                <p>Jam Selesai: <input type="text" name="jam_selesai"></p>
                <p>Tipe Event: <input type="text" name="tipe"></p>
            </form>
        </div>
        <ul class="list">
            <p>Lokasi Event</p>
            <li id="ticket-list" style="margin-bottom: 8px;">
                <form>
                    <input type="text" name="nama_gedung">
                    <input type="text" name="kota">
                    <input type="text" name="alamat">
                    <button type="button">Hapus row</button>
                </form>
                <form>
                    <input type="text" name="nama_gedung">
                    <input type="text" name="kota">
                    <input type="text" name="alamat">
                    <button type="button">Hapus row</button>
                </form>
            </li>
            <button type="button">Tambah row</button>
            <p>Daftar Kelas Tiket</p>
            <li id="ticket-list" style="margin-bottom: 8px;">
                <form>
                    <input type="text" name="nama_kelas">
                    <input type="text" name="tarif">
                    <input type="text" name="kapasitas">
                    <button type="button">Hapus row</button>
                </form>
                <form>
                    <input type="text" name="nama_kelas">
                    <input type="text" name="tarif">
                    <input type="text" name="kapasitas">
                    <button type="button">Hapus row</button>
                </form>
            </li>
            <button type="button">Tambah row</button>
        </ul>

        <div class="transaction">
            <button type="button">Update Event</button>
            <button type="button">Cancel</button>
        </div>
    </div>

</div>

{% endblock %}

event/templates/event_list.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'event_list.css' %}">
{% endblock %}

{% block title %} Event {% endblock %}

{% block body %}

<div class="card">
  <h2 class="card-title">Events</h2>
  
  <div class="card-content">
    {% if 'organizer' in request.session.role %}
      <div class="btn-wrapper">
        <a class="btn btn-info" href="{% url 'event:create' %}">
          Buat Event Baru
        </a>
    {% endif %}
    </div>
    {% if page_obj %}
      <table class="event-list">
        <tr>
          <th>No</th>
          <th>Tema Event</th>
          <th>Nama Event</th>
          <th>Organizer</th>
          <th>Lokasi</th>
          <th>Tanggal</th>
          <th>Jam</th>
          <th>Kapasitas</th>
          {% if request.session.role is None or 'visitor' in request.session.role %}
            <th>Pesan Tiket</th>
          {% else %}
            <th>Edit Event</th>
            <th>Delete</th>
          {% endif %}
        </tr>
        
        {% for event in page_obj %}
          <tr class="t-row">
            <td>{{ event.no }}</td>
            <td>
              {% for theme in event.tema %}
                {{ theme }}{{ forloop.last|yesno:",&#44;"|safe }}
              {% endfor %}
            </td>
            <td>{{ event.nama }}</td>
            <td>{{ event.organizer.nama }}</td>
            <td>
              {% for location in event.lokasi %}
                {{ location }}{{ forloop.last|yesno:",&#44;"|safe }}
              {% endfor %}
            </td>
            <td>{{ event.tanggal_mulai }} - {{ event.tanggal_selesai }}</td>
            <td>{{ event.jam_mulai }} - {{ event.jam_selesai }}</td>
            <td>{{ event.kapasitas_total_tersedia }}</td>
            {% if request.session.role is None or 'visitor' in request.session.role %}
              <td>
                <a class="btn btn-success" href="{% url 'tiket:buy' event.id_event %}">
                  Pesan Tiket
                </a>
              </td>
            {% else %}
              {% if event.organizer.email == request.session.email %}
                <td>
                  <a class="btn btn-warning" href="{% url 'event:edit' event.id_event %}">
                    Edit  
                  </a>
                </td>
                <td>
                  <input type="submit" value="Hapus" class="btn btn-danger"
                  onclick="return confirm(`Apakah anda yakin untuk menghapus Event ini?`);">
                </td>
              {% else %}
                <td></td><td></td>
              {% endif %}
            {% endif %}
          </tr>
        {% endfor %}
      </table>

      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
    
          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>

    {% else %}
      <h3>Tidak ada event saat ini...</h3>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'base.css' %}">
  {% block head %}
  {% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">EVENT+</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Events</a>
          </li>
          {% if request.session.role is None or 'user' in request.session.role %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth:register' %}">Register</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
            </li>
            {% if request.session.role == 'visitor' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'e_wallet:list' %}">E-Wallet</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}

  {% block script %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
    integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>

tiket/templates/pesan_tiket.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'pesan_tiket.css' %}">
{% endblock %}

{% block title %} Pesan Tiket {% endblock %}

{% block body %}
<div class="card">
    <h2 class="card-title">Pesan Tiket</h2>

    <div class="card-content">
        <div class="desc">
            <p>Tema Event: {{ desc.tema }}</p>
            <p>Nama Event: {{ desc.nama }}</p>
            <p>Deskripsi: {{ desc.deskripsi }}</p>
            <p>Tanggal: {{ desc.tanggal }}</p>
            <p>Lokasi Event: {{ desc.lokasi }}</p>
            <p>Tipe Event: {{ desc.tipe }}</p>
        </div>


        <ul class="list">
            {% for ticket in tickets %}
            <li id="ticket-list" style="margin-bottom: 8px;">
                {{ ticket.nama_kelas }} - {{ ticket.tarif }} - Kap: {{ ticket.kapasitas }} - Kap tersedia: {{ ticket.kapasitas_tersedia }}
                <form>
                    <input type="text" name="nama_pendaftar">
                    <input type="text" name="email_pendaftar">
                    <button type="button">Hapus row</button>
                </form>
                <form>
                    <input type="text" name="nama_pendaftar">
                    <input type="text" name="email_pendaftar">
                    <button type="button">Hapus row</button>
                </form>
            </li>
            <button type="button">Tambah row</button>
            {% endfor %}
        </ul>

        <div class="transaction">
            <button type="button">Buat transaksi</button>
            <button type="button">Cancel</button>
        </div>
    </div>
    
</div>

{% endblock %}

tiket/templates/transaksi_tiket.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'transaksi_tiket.css' %}">
{% endblock %}

{% block title %} Transaksi Tiket {% endblock %}

{% block body %}
<div class="card">
    <h2 class="card-title">Transaksi</h2>

    <div class="card-content">
        <table class="transaction-list">
            <tr>
                <th>No.</th>
                <th>Tanggal Transaksi</th>
                <th>Waktu Transaksi</th>
                <th>Status Transaksi</th>
                <th>Total Bayar</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            {% for trans in transactions %}
            <tr class="row">
                <td>{{ forloop.counter }}</td>
                <td>{{ trans.tanggal }}</td>
                <td>{{ trans.waktu }}</td>
                <td>{{ trans.status }}</td>
                <td>{{ trans.total_bayar }}</td>
                <td>
                    <a href="{% url 'tiket:update' %}">
                        <button type="button">Edit</button>
                    </a>
                </td>
                <td>
                    <input type="submit" value="Hapus" class="btn"
                    onclick="return confirm(`Apakah anda yakin untuk menghapus Transaksi Event ini?`);">
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

</div>

{% endblock %}

tiket/templates/update_transaksi.html
{% extends 'base.html' %}
{% load static %}
{% load extra_filters %}

{% block head %}
<link rel="stylesheet" href="{% static 'pesan_tiket.css' %}">
{% endblock %}

{% block title %} Update Transaksi {% endblock %}

{% block body %}
<div class="card">
    <h2 class="card-title">Update Transaksi</h2>

    <div class="card-content">
        <div class="desc">
            <p>Tema Event: {{ desc.tema }}</p>
            <p>Nama Event: {{ desc.nama }}</p>
            <p>Deskripsi: {{ desc.deskripsi }}</p>
            <p>Tanggal: {{ desc.tanggal }}</p>
            <p>Lokasi Event: {{ desc.lokasi }}</p>
            <p>Tipe Event: {{ desc.tipe }}</p>
        </div>


        <ul class="list">
            {% for ticket in tickets %}
            <li id="ticket-list" style="margin-bottom: 8px;">
                {{ ticket.nama_kelas }} - {{ ticket.tarif }} - Kap: {{ ticket.kapasitas }} - Kap tersedia: {{ ticket.kapasitas_tersedia }}
                <form>
                    <input type="text" name="nama_pendaftar">
                    <input type="text" name="email_pendaftar">
                    <button type="button">Hapus row</button>
                </form>
                <form>
                    <input type="text" name="nama_pendaftar">
                    <input type="text" name="email_pendaftar">
                    <button type="button">Hapus row</button>
                </form>
            </li>
            <button type="button">Tambah row</button>
            {% endfor %}
        </ul>

        <div class="transaction">
            <a href="{% url 'tiket:transaksi' %}">
                <button class="btn" type="button">Update Transaksi</button>
            </a>
            <a href="{% url 'tiket:transaksi' %}">
                <button class="btn" type="button">Cancel</button>
            </a>
        </div>
    </div>
    
</div>

{% endblock %}

user/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'edit_profile.css' %}">
{% endblock %}

{% block title %} Profil | Edit {% endblock %}

{% block body %}
  <div class="card">
    <h2 class="card-title">
      Edit Profil
      {% if "visitor" in request.session.role %}
        Pengunjung
      {% else %}
        Organizer
      {% endif %}
    </h2>

    <form action="" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="field-wrapper">
          <div class="center">
            {{ field.label_tag }}
            {{ field }}
          </div>
          {{ field.errors }}
        </div>
      {% endfor %}
      <input class="btn btn-primary" type="submit" value="Simpan Profil">
      <a href="{% url 'user:profile' %}">
        <button class="btn btn-secondary" type="button">Cancel</button>
      </a>
    </form>
  </div>
{% endblock %}

user/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'profile.css' %}">
{% endblock %}

{% block title %} Profil {% endblock %}

{% block body %}
  <div class="card">
    <h2 class="card-title">
      Profil
      {% if "visitor" in request.session.role %}
        Pengunjung
      {% else %}
        Organizer
      {% endif %}
    </h2>

    <div class="field-wrapper">
      <div class="center">
        <table>
          {% for field in form %}
            <tr>
              <td class="label">{{ field.label }}</td>
              <td class="value">: {{ field.value }}</td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
    <a class="btn btn-primary" href="{% url 'user:edit_profile' %}">
      Edit Profil
    </a>
  </div>
{% endblock %}